### PR TITLE
Wallpaper config Menu

### PR DESCRIPTION
**Pull request by noahbechtel**
Creates a settings entry to manage wallpaper, better performance, able to order entries in the same manner as home screen icons.

### CODE REVIEW

**Comment by cuu** [comment]
thanks for the PR

here is a little edits

I think
```
        files_path = '/home/cpi/launcher/skin/' + \
            config.SKIN + '/Menu/GameShell/Wallpaper'
```
should be 
```
        files_path = config.SKIN + '/Menu/GameShell/Wallpaper'
```
because now We have the skin selections  in Settings 
the addtional skins folders will be  under ~/skins/

so just use config.SKIN

**Comment by cuu** [comment]
and in config.py
there are
```
<< << << < HEAD
Wallpaper = ""
== == == =
```
these are not python code

and why in your run.py
you removed 
```
release_self_fds():
```
this is for a file descriptors bug in launcher

and PreparationInAdv() should not in run.py
it must in config.py

**Comment by cuu** [comment]
and if you want use .wallpaper for wallpaper
you should add 
```
sys.py/.wallpaper 
```
in .gitignore first

**Comment by noahbechtel** [comment]
Ok, sorry about that, still working on my merge abilities! Thanks for the heads up, should be in the clear.

**Comment by cuu** [comment]
We welcome PR. If my English is stiff, please forgive me. My English is still poor.
(a lot come from machine translator)

and if you want to enable Wallpaper to be in Settings Menu, just put a line in 
`Menu/GameShell/10_Settings/list_page.py`
like:
```
...
                         ["","Skins","Skins"],
                         ["","Wallpaper","Wallpapers"],
....
```
and I tried your code ,still has problems

first 
delete the whole  `PreparationInAdv()` in sys.py/run.py
move the logic code of wallpaper to `sys.py/config.py:PreparationInAdv`

second
in `Menu/GameShell/10_Settings/Wallpaper/__init__.py` 
replace all `fonts["xxxxxx"]` to be  `MySkinManager.GiveFont("xxxx")`
delete all `from UI.fonts import fonts`
there is no UI.fonts anymore

you can test the launcher on PC ,linux 

kind regards

**Comment by noahbechtel** [comment]
Hello, thank you for your patience, I will test the new edits tonight. Thank you for your helpful advice.

**Pull request closed without merging**
