### PR TITLE
Fix UX for XBOX layout

### PR DESCRIPTION
**Pull request by infernalmaster**
I changed meaning of buttons A and B for XBOX layout.
 "A" - "Enter/Accept"
"B" - "Escape/Back". 
I was opposite to it, so it confuses me every time after using real XBOX.

So "A" works the same as "Start" button and "B" as "Menu" so I added helpers `IsKeyStartOrA` ` IsKeyMenuOrB` and used them in every place where it was possible

### CODE REVIEW

**Comment by cuu** [comment]
But I will restore the keys "never used" later

**Comment by infernalmaster** [comment]
Yes, sure. I just want to explain more what I did and why I did that.

1. I swapper meaning of "A" and "B" to be more natural even in codebase. Now:
A - Enter
B - Escape
2.  Removed this key
```
GameShell["Enter"] = pygame.K_k
```
There is no such button on GameShell, I was more semantic alias for "B":
`GameShell["B"]    = pygame.K_k`
https://github.com/infernalmaster/launcher/blob/ca729397430f2ece112275244ba5b9603f58c9fa/sys.py/UI/keys_def.py#L28
And I added helper `IsKeyStartOrA` for this purpose.   

3. Renamed button "Space" to "Select" as it is on GameShell

https://github.com/clockworkpi/launcher/pull/170/files#diff-ff3e891a041114c909f83643acbe790bR69


4. About this 2 button
```
GameShell["Vol-"] = pygame.K_SPACE
GameShell["Vol+"] = pygame.K_RETURN
```
They were binded the same as this 2:
```
GameShell["Select"] = pygame.K_SPACE
GameShell["Start"] = pygame.K_RETURN
```

But they should work only if 'Shift' is pressed, so looks like this is mistake. According to this https://github.com/infernalmaster/launcher/blob/master/sys.py/run.py#L380 they should be 

```
GameShell["Vol-"] = pygame.K_KP_MINUS
GameShell["Vol+"] = pygame.K_KP_PLUS
````
So If you want to restore them, you may use them there.

5. I also change button for adding to favorites from "B" to "Select" to make UX more consistent.
https://github.com/clockworkpi/launcher/pull/170/files#diff-7104b0bc249993921c86584bf9ef747dR102
*And now here is no footer_bar hint for this action. This should be fixed*


And looks like that's all what I did.

**Comment by cuu** [comment]
Enter is a button  Gs when you press shift button + Start/Select ,I could not remember which one is
pretty sure is the right one 

and after I tried the new layout
I must say ,it confused me
the XBOX layout maybe like what you said is ok,but what about SNES?

And most of the users already get used to the keyboard layout A and B 

not much need to change that 
I'll consider to rollback it

**Comment by infernalmaster** [comment]
I'm sorry if my comments offended you somehow. I just want to improve my user experience with this device 🚀 
I perfectly understand that there many changes in my commit and there is a risk to break something.

**Comment by cuu** [comment]
yes you are right

What you said is too serious. There is no such thing at all. My English is not good enough to express my meaning well, which makes you misunderstand.

First of all, it's not me, it's my boss who decides this button habit
So I can't decide whether to change it or not, so we'll do it again when we have time.
Finally, thank you very much for your participation. I hope that communication misunderstanding will not arise because of  language problem.

**Pull request merged**
